In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv("movie.csv")

In [3]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
movies.shape

(27278, 3)

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  27278 non-null  int64
 1   title    27278 non-null  object
 2   genres   27278 non-null  object
dtypes: int64(1), object(2)
memory usage: 639.5+ KB

In [6]:
movies.describe()

             movieId
count   27278.000000
mean    59855.480570
std     44429.314697
min         1.000000
25%      6931.250000
50%     68068.000000
75%    100293.250000
max    131262.000000

In [7]:
movies.dtypes

movieId     int64
title      object
genres     object
dtype: object

In [8]:
movies.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [9]:
movies.duplicated().sum()

np.int64(0)

In [10]:
movies = movies.fillna('')

In [11]:
movies.head(1)

   movieId             title                                       genres
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy

In [13]:
movies['features'] = movies['genres'] #We will recommend all movies based on the genres

In [14]:
#Now we will convert the texts into numbers

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(movies['features'])

In [19]:
similarity = cosine_similarity(feature_vectors)

In [20]:
def recommend_movie(movie_name):

    movie_name = movie_name.lower()

    movies['title_lower'] = movies['title'].str.lower()

    if movie_name not in movies['title_lower'].values:
        print("Movie not found")
        return

    index = movies[movies['title_lower'] == movie_name].index[0]

    similarity_scores = list(enumerate(similarity[index]))

    sorted_movies = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    print("Recommended Movies:\n")

    count = 1

    for movie in sorted_movies[1:11]:
        movie_index = movie[0]
        print(count, ".", movies.iloc[movie_index]['title'])
        count += 1

In [21]:
recommend_movie("Toy Story (1995)")

Recommended Movies:

1 . Antz (1998)
2 . Toy Story 2 (1999)
3 . Adventures of Rocky and Bullwinkle, The (2000)
4 . Emperor's New Groove, The (2000)
5 . Monsters, Inc. (2001)
6 . DuckTales: The Movie - Treasure of the Lost Lamp (1990)
7 . Wild, The (2006)
8 . Shrek the Third (2007)
9 . Tale of Despereaux, The (2008)
10 . Asterix and the Vikings (Astérix et les Vikings) (2006)

In [22]:
recommend_movie("Jumanji (1995)")

Recommended Movies:

1 . Kids of the Round Table (1995)
2 . Indian in the Cupboard, The (1995)
3 . NeverEnding Story III, The (1994)
4 . Escape to Witch Mountain (1975)
5 . Darby O'Gill and the Little People (1959)
6 . Return to Oz (1985)
7 . NeverEnding Story, The (1984)
8 . NeverEnding Story II: The Next Chapter, The (1990)
9 . Santa Claus: The Movie (1985)
10 . Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)

In [24]:
recommend_movie("Jurassic Park")

Movie not found